{% set name = "mosfit" %}
{% set version = "0.7.6" %}
{% set sha256 = "d015c4067546571cc57b6077830c7c28c82f321152cadc889e62d52897dd5e2b" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - scipy !=0.19.0
    - astrocats
    - astropy
    - cython
    - emcee
    - extinction
    - inflect
    - matplotlib
    - mpi4py
    - nbstripout
    - numexpr
    - palettable
    - schwimmbad
    - seaborn
    - six
  run:
    - python
    - scipy !=0.19.0
    - astrocats
    - astropy
    - cython
    - emcee
    - extinction
    - inflect
    - matplotlib
    - mpi4py
    - nbstripout
    - numexpr
    - palettable
    - schwimmbad
    - seaborn
    - six

test:
  imports:
    - mosfit
  files:
    - forge_test.sh
  source_files:
    - test.py
    - test.sh
    - mosfit/tests/LSQ12dlf.json
    - mosfit/tests/SN2006le.json
  commands:
    - time bash ./forge_test.sh  # [not win]

about:
  home: http://github.com/guillochon/mosfit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Modular fitter for astrophysical transients'

  description: |
    mosfit is a package that performs fitting of semi-analytical model predictions
    to observed astrophysical transients. Data can be provided by the user or pulled
    automatically from the Open Astronomy catalogs.
  doc_url: http://mosfit.readthedocs.io/
  dev_url: https://github.com/guillochon/mosfit

extra:
  recipe-maintainers:
    - guillochon
    - mnicholl
    - pkgw
