{% set name = "mosfit" %}
{% set version = "1.1.1" %}
{% set sha256 = "da777b6295d9a5d54cbe65ce82acd26c87dbb9b485f003f341a9b8115655f8d9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - scipy !=0.19.0
    - astrocats
    - astropy
    - cython
    - emcee
    - extinction
    - inflect
    - matplotlib
    - mpi4py
    - nbstripout
    - numexpr
    - palettable
    - schwimmbad
    - seaborn
    - six
  run:
    - python
    - scipy !=0.19.0
    - astrocats
    - astropy
    - cython
    - emcee
    - extinction
    - inflect
    - matplotlib
    - mpi4py
    - nbstripout
    - numexpr
    - palettable
    - schwimmbad
    - seaborn
    - six

test:
  imports:
    - mosfit
  files:
    - forge_test.sh
  source_files:
    - test.py
    - test.sh
    - mosfit/tests/LSQ12dlf.json
    - mosfit/tests/SN2006le.json
    - mosfit/tests/event_list.txt
    - mosfit/tests/PTF10hgi.txt
  commands:
    - time bash ./forge_test.sh  # [not win]

about:
  home: http://github.com/guillochon/mosfit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Modular fitter for astrophysical transients'

  description: |
    mosfit is a package that performs fitting of semi-analytical model predictions
    to observed astrophysical transients. Data can be provided by the user or pulled
    automatically from the Open Astronomy catalogs.
  doc_url: http://mosfit.readthedocs.io/
  dev_url: https://github.com/guillochon/mosfit

extra:
  recipe-maintainers:
    - guillochon
    - mnicholl
    - pkgw
