{% set name = "mosfit" %}
{% set version = "1.2" %}
{% set sha256 = "15f4ddd97b0563c34b8dacbd341591bb95f2c272236f276bff494e9d6ca0b3c8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - scipy !=0.19.0
    - astrocats
    - astropy-base
    - cython
    - emcee
    - extinction
    - inflect
    - matplotlib-base
    - mpi4py  # [not win]
    - nbstripout
    - numexpr
    - palettable
    - schwimmbad
    - seaborn
    - six
  run:
    - python
    - scipy !=0.19.0
    - astrocats
    - astropy-base
    - cython
    - emcee
    - extinction
    - inflect
    - matplotlib-base
    - mpi4py  # [not win]
    - nbstripout
    - numexpr
    - palettable
    - schwimmbad
    - seaborn
    - six

test:
  requires:
    - git
    - openssh  # [not win]
    - xorg-libx11
  imports:
    - mosfit
  files:
    - forge_test.sh
  source_files:
    - test.py
    - test.sh
    - mosfit/tests/LSQ12dlf.json
    - mosfit/tests/SN2006le.json
    - mosfit/tests/event_list.txt
    - mosfit/tests/PTF10hgi.txt
  commands:
    - time bash ./forge_test.sh  # [not win]

about:
  home: https://github.com/guillochon/mosfit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modular fitter for astrophysical transients

  description: |
    mosfit is a package that performs fitting of semi-analytical model predictions
    to observed astrophysical transients. Data can be provided by the user or pulled
    automatically from the Open Astronomy catalogs.
  doc_url: https://mosfit.readthedocs.io/
  dev_url: https://github.com/guillochon/mosfit

extra:
  recipe-maintainers:
    - gmzsebastian
    - guillochon
    - mnicholl
    - pkgw
