{% set name = "mosfit" %}
{% set version = "0.5.10" %}
{% set sha256 = "6d6c43ad045a8cbafe51afd7ae9406e044db30f19c794e902d8c241fc7cf8b28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - testing.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - mosfit = mosfit.main:main

requirements:
  build:
    - python
    - setuptools
    - scipy
    - astrocats
    - astropy
    - cython
    - emcee
    - extinction
    - inflect
    - matplotlib
    - mpi4py
    - nbstripout
    - numexpr
    - palettable
    - schwimmbad
    - seaborn
    - six
  run:
    - python
    - scipy
    - astrocats
    - astropy
    - cython
    - emcee
    - extinction
    - inflect
    - matplotlib
    - mpi4py
    - nbstripout
    - numexpr
    - palettable
    - schwimmbad
    - seaborn
    - six

test:
  imports:
    - mosfit
  source_files:
    - test.py
    - test.sh
    - mosfit/tests/LSQ12dlf.json
    - mosfit/tests/SN2006le.json
  commands:
    - ./test.sh  # [not win]

about:
  home: http://github.com/guillochon/mosfit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Modular fitter for astrophysical transients'

  description: |
    mosfit is a package that performs fitting of semi-analytical model predictions
    to observed astrophysical transients. Data can be provided by the user or pulled
    automatically from the Open Astronomy catalogs.
  doc_url: http://mosfit.readthedocs.io/
  dev_url: https://github.com/guillochon/mosfit

extra:
  recipe-maintainers:
    - guillochon
    - mnicholl
    - pkgw
