travis:
  secure:
    BINSTAR_TOKEN: bDaSY/mzYCLiKcdZQ9zEasIh/f0sRIPyBF8iXeuoiVqYBy5Er93ieOfRuZfWNoLX3wLHZdPvjUtzRA8G3ov0q50MvSdYtfaNQLZmnG/1dGSkcWpBhUhMfql/FHPeohi4QCzSSMmCk7U82/c8u0NnL5jA6ITJlpD2YdaY+ofD6Yodpwa/AOUliNUy2QzISUYEpvmYwa/vRfvOiTqsVCgghPeetsm10bfwXI1liq+vAmXPzPO+hx6CA7RRxsU5NBgUZy9ft1yKuoj9/KojCF256j/EU3A50vyU318xJVUQFoJFGcbhBnQP1sMvCcL4/TZpLJ3m7cBxWSeRu9pFQoNazy+NLle14Aaee1qmLjCJTAaCm/gzn1il3hiK6VNZ/6sVdCL/SY5zlBhm07qjtiMzXMMOD1A6+NxChFWswmnBLqke/OTQArkAHc5EF+fXsYeVbgCqw/gnbnBjdMOwoiET78FPCxyQLGGj3U3ZIDB+ECysluLHIWDahU45hsVXt2KEAwcM1QGCvG8hBS95tSwxWdcVGVUVin4TW+ihzwh/dCIi6Nq0mEvdhpd1yRTKBwNt3G0yCaiGqN+QnZi7/SskxWMk7QGC6tfI5dvuNHqJTjjx6ONXYmME4sDboyX5emsj+JCkM4FL3q3mK47ODceYGWwBv+km1xu7HNJwS5TWK+g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
