travis:
  secure:
    BINSTAR_TOKEN: bNCDatYhj8Yg31U2fKRXDoDwm2a4ufcwtg6U1g644BwqHn8d9fNF1VoctAebcTBgWNq2r1Wx7MC1ReG9V+PmrrE+jYbz0puwcTEgEpOgf03fwxEgY1Q8i2yN0ogRw830ZbgcIbvAQtsl60tPIgSumDZiONbbgfvw8cSF7YrWceqIzNszczDRiwCdiqITt0EQOGtkt1B7jnvYrQAagHyWTTYw6bWpiwsC8MlMDYsVwnxRDaIsV+QyTOlM6H17GhUBqpYO2V2s8ft00mZQQomLcGcZPnlLt9b/fNbj3Q/1KiN9LKfOv4XaZKif6+53RiAKZB2Izx2RWM5ARmCGjjgKRoEvve2/ZpbU9Nib/WjsXUvqGkkU8SCcVKvsmAn6EwghbEOj8CYnwpqYj+l9Pt7yWk7n7KrHtklfz32A1BKgKsHt7rbqFpXGSk6PTzME9i0GU8xB9bacCev2/10PgKokur48wzzTkKJiUwjxbKK7hoSzTKs4Y7QdklTXCK9aWnql6m6/LMrqlWZyoAHTyAvJYU0MDsDI4Ugfkg4H+zknY0pmaK1O8HrQptiXovfKntNzHtgOiy8D1plG/9dB0yYe2KW+mVxlDbofnyoXRsJpsEh8N+U/dcEzFze0vcxViO+QtYF1COII3fNqU67FQTHDhvD/Pm8qU9OK31+ANE1sBxo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
